server:
  port: 88
spring:
  application:
    name: cloud-beakermall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://cloud-beakermall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: route_renren_fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
#            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
