spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: cloud-beakermall
  application:
    name: cloud-beakermall-third-party
server:
  port: 30000
